### ISSUE TITLE
Player skip time with double-tap

### ISSUE THREAD

**Issue by marcheimendinger** [SRGSSR/playsrg-apple#197]
### Issue type

Feature request

### Description of the problem

Add a double-tap skip time feature similar to what YouTube does.

Left half part of the screen is backward 10s and right part is forward 10s.

**Comment by defagos** [comment]
Thanks for the input. I agree with you, this is something I regularly miss in our player, now that YouTube somehow made it a standard.

This feature is something that was already discussed within the team in the past, but it requires a bit of thought. As double taps are currently wired to fit / fill behavior, we would namely need a different gesture similar to what YouTube is doing, like a pinch, or a dedicated button, so that this feature is preserved. We also have many overlapping gestures which requires careful thought so that no conflict arises among them. But this is definitely something we could consider as part of UX improvements in the future.

**Comment by defagos** [comment]
I started implementing support for skips with double taps in our official SRG SSR player, as described in a corresponding [issue](https://github.com/SRGSSR/srgletterbox-apple/issues/261).

This is a first step to see whether such gestures are viable. Some UX / UI discussions and a team agreement are still required before this feature can be officially released, but I am quite confident the result should meet our standards 🙂

**Comment by defagos** [comment]
Here is the plan:

- [ ] Implement support for new gesture without UI / UX details, see [Letterbox issue](https://github.com/SRGSSR/srgletterbox-apple/issues/261).
- [ ] Integrate in nightly Play build for tests within the team. In particular the feature must integrate with the existing Play pinch iPad gesture: Player with details > Full screen > Zoomed, where > is a pinch gesture (and of course in the other direction).
- [ ] Discuss remaining UI / UX questions, see [Letterbox issue](https://github.com/SRGSSR/srgletterbox-apple/issues/261) and implement based on team decisions.
- [ ] Deliver, likely in release 2.6.1.

**Comment by defagos** [comment]
@marcheimendinger The feature is available in our beta channel. You can register for the beta channel (if not already the case) directly from within the application settings if you want to access the feature earlier. You will then be able to install the beta for the upcoming version 3.6.1 in which the feature will be delivered.

We might still tweak a few things before the final release (e.g. the skip intervals) but the feature itself should be pretty much complete. Thanks for your patience. We hope you'll enjoy it.

**Comment by pyby** [comment]
Available in the public [3.6.1](https://github.com/SRGSSR/playsrg-apple/releases/tag/ios%2F3.6.1-386) iOS release.
Thank you for the proposition submitted here.
